### ISSUE TITLE
Update page: Cookies

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#108]
File: [wordpress/cookies.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/wordpress/cookies.md)

This page needs a general review and update.

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [ ] General review and updating
- [ ] Check the external links to browsers and add new ones, like Brave.

**Comment by AkireOrl** [comment]
Assign me, please
