### ISSUE TITLE
Update page: Editing Files

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#110]
File: [wordpress/edit-files.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/wordpress/edit-files.md)

This page needs a general review and update.

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [ ] General review and updating

**Comment by Crixu** [comment]
solved with #124 124
