### ISSUE TITLE
Update page: Debugging on WordPress

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#165]
File: [debug/debug-wordpress.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/debug/debug-wordpress.md)

This page needs a general review and update.

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [ ] General review and updating

**Comment by cpaloukas** [comment]
I reviewed and updated here [here](https://github.com/cpaloukas/Advanced-administration-handbook/blob/main/debug/debug-wordpress.md) .
