### ISSUE TITLE
Update page: Resources for Building on WordPress

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#167]
File: [resources/index.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/resources/index.md)

This page needs a general review and update.

Check the links, if they are allowed or not.

If you add documentation from another WordPress.org page, indicate it in the Changelog or in the comments of this issue.

### To-Do

- [x] General review and updating
- [x] Check all the links

**Comment by pieteee** [comment]
other than [this document](https://developer.wordpress.org/advanced-administration/wordpress/css/) in [CSS](https://developer.wordpress.org/advanced-administration/wordpress/css/), everything looks good.

**Comment by javiercasares** [comment]
Internally marked as OK, and ready for review :)

Thank you, @pieteee for the review.
