### ISSUE TITLE
Broken Link for `W3 Total Cache` on Optimization/Caching page

### ISSUE THREAD

**Issue by pfefferle** [WordPress/Advanced-administration-handbook#174]
## Issue Description

The link to `W3 Total Cache` points to `https://wordpress.org/extend/w3-total-cache/` instead of `https://wordpress.org/plugins/w3-total-cache/`

## URL of the Page with the Issue

https://wordpress.org/support/article/optimization/#Caching

## Section of Page with the issue

Caching/W3 Total Cache

## Why is this a problem?

Broken link

## Suggested Fix

`https://wordpress.org/plugins/w3-total-cache/` instead of `https://wordpress.org/extend/w3-total-cache/`

**Comment by stevenlinx** [comment]
I've removed all references to cache plug-ins. Instead, asking the user to search for them in the plug-in directory.

The page still need more revisions, as outlined in #161, but the changes pertaining to "Caching Plugins" in this Issue is complete.
