### ISSUE TITLE
Update page: FAQ Troubleshooting

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#176]
File: [resources/faq.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/resources/faq.md)

This page needs a general review. Also, probably all links go to deprecated URL, so need to be updated.

### To-Do

- [x] Check and fix all the links
- [x] Do a general review

**Comment by nouman17610** [comment]
Hello @javiercasares,
I want to contribute to this page, please assign me the links fixing and general review.
Thank you.

**Comment by RitchelLauron** [comment]
I'd like to work on this topic @javiercasares. Thanks!
