### ISSUE TITLE
Update page: Editing Files

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#194]
### What

From [#673](https://github.com/WordPress/Documentation-Issue-Tracker/issues/673), 1 text editor needs to be removed, and 2 need new links.

### Where

File: [wordpress/edit-files.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/wordpress/edit-files.md)

### To-Do
[ ] Remove Atom since it has been deprecated.
[ ] Correct Sublime Text link to http://www.sublimetext.com/ since it is currently linked to a deprecated version.
[ ] Correct NetBeans link to https://netbeans.apache.org/ since it is currently linked to its documentation.

**Comment by KshitizRana** [comment]
May I work on this issue ?

**Comment by KshitizRana** [comment]
This issue has been resolved please close it.

**Comment by Crixu** [comment]
Closed with PR #235
