### ISSUE TITLE
Update page: Cookies

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#195]
### What

From [#740](https://github.com/WordPress/Documentation-Issue-Tracker/issues/740), add wp_test_cookie to document.

### Where

File: [wordpress/cookies.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/wordpress/cookies.md)

### To-Do
[ ] Add information about the "wordpress_test_cookie".

**Comment by javiercasares** [comment]
https://github.com/WordPress/Documentation-Issue-Tracker/issues/756

**Comment by apermo** [comment]
@zzap
