### ISSUE TITLE
Changing The Site URL protocol 

### ISSUE THREAD

**Issue by zzap** [WordPress/Advanced-administration-handbook#310]
> It would be better to write https: instead of http: in the URLs. There are hardly any websites that still use http:. It also leads to confusion for new users when a manual "prescribes" such URLs.

Reported in docs salck by https://profiles.wordpress.org/la-geek/

URL: https://developer.wordpress.org/advanced-administration/upgrade/migrating/#changing-the-site-url

**Comment by javiercasares** [comment]
Done at #311
