### ISSUE TITLE
Regression: .htaccess examples use invalid syntax (extraneous backslashes)

### ISSUE THREAD

**Issue by jani** [WordPress/Advanced-administration-handbook#318]
In https://github.com/WordPress/Advanced-administration-handbook/blob/main/server/httpd.md, .htaccess introduce syntax errors by using extraneous backslashes, which causes Apache to return 500 Internal Server Error for any website using these examples.

```
# BEGIN WordPress

RewriteEngine On
RewriteRule .\* - \[E=HTTP\_AUTHORIZATION:%{HTTP:Authorization}\]
RewriteBase /
RewriteRule ^index\\.php$ - \[L\]
RewriteCond %{REQUEST\_FILENAME} !-f
RewriteCond %{REQUEST\_FILENAME} !-d
RewriteRule . /index.php \[L\]

# END WordPress
```

should be

```
# BEGIN WordPress

RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]

# END WordPress
```

and so on.

**Comment by leendertvb** [comment]
Vote!

This is already an issue since the last changes at 2023-04-25. I can confirm the current code results in a 500 error.

**Comment by jani** [comment]
https://developer.wordpress.org/advanced-administration/server/web-server/httpd/ now is updated with the approved pull request #320.
