### ISSUE TITLE
New page: Configuring Wildcard Subdomains

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#88]
File: [server/subdomains-wildcard.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/server/subdomains-wildcard.md)

Original content: [Configuring Wildcard Subdomains](https://wordpress.org/support/article/configuring-wildcard-subdomains/)

- [ ] Copy the content
- [ ] Check all the links

**Comment by nuriarai** [comment]
Núria

**Comment by javiercasares** [comment]
Related #123
