### ISSUE TITLE
Update page: wp-config.php

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#89]
Add, as the first section, this content.

File: [wordpress/wp-config.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/wordpress/wp-config.md)

Original content: [Editing wp-config.php](https://wordpress.org/support/article/editing-wp-config-php/)

- [ ] Copy the content
- [ ] Check all the links

**Comment by acastellano** [comment]
Hola @javiercasares me pongo con esta

**Comment by acastellano** [comment]
@javiercasares actualmente este archivo ya tiene contenido de esta url https://developer.wordpress.org/apis/wp-config-php/ ¿dónde se debería añadir el contenido de https://wordpress.org/documentation/article/editing-wp-config-php/ ?

**Comment by javiercasares** [comment]
> @javiercasares actualmente este archivo ya tiene contenido de esta url https://developer.wordpress.org/apis/wp-config-php/ ¿dónde se debería añadir el contenido de https://wordpress.org/documentation/article/editing-wp-config-php/ ?

Al inicio del documento, en la parte superior... como el primer bloque.

**Comment by acastellano** [comment]
Ok @javiercasares 
Contenido añadido. Sugiero adaptar el final del primer párrafo al contenido ya que hace referencia a una página que tiene lo mismo que se comenta a continuación del texto. "this [page](https://developer.wordpress.org/apis/wp-config-php/) should help."
