### ISSUE TITLE
New page: Feeds

### ISSUE THREAD

**Issue by javiercasares** [WordPress/Advanced-administration-handbook#93]
Some sections of this document are more technical than others. Only those sections should be moved.
- NO - Introduction to Feeds _(General support)_
- **YES** - WordPress Built-in Feeds _(Advanced support)_
- NO - Finding Your Feed URL _(General support)_
- **YES** - Adding Feeds _(Advanced support)_

File: [wordpress/feed.md](https://github.com/WordPress/Advanced-administration-handbook/blob/main/wordpress/feed.md)

Original content: [WordPress Feeds](https://wordpress.org/support/article/wordpress-feeds/)
- [WordPress Built-in Feeds](https://wordpress.org/support/article/wordpress-feeds/#wordpress-built-in-feeds)
- [Adding Feeds](https://wordpress.org/support/article/wordpress-feeds/#adding-feeds)

- [ ] Copy the content
- [ ] Check all the links

**Comment by javi-g** [comment]
me ocupo, vale?

**Comment by javiercasares** [comment]
Related #121
